root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/goaway"
args_bin = [
    "--dnsport=6121",
    "--webserverport=8080",
    "--loglevel=0",
    "--disablelogging=false",
    "--auth=false",
    "--statisticsRetention=7",
    "--dev=true",
]
cmd = 'go build -o goaway -ldflags="-X main.version=0.0.0 -X main.commit=ead2d7830add26d53ecab3c907a290f0cdc1e078 -X main.date=2025-04-11T13:37:56Z" -o ./tmp/goaway .'
exclude_dir = [
    "assets",
    "tmp",
    "vendor",
    "client/dist",
    "client/node_modules",
    "test",
    "resources",
]
include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "jsx", "ts", "tsx"]

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
clean_on_exit = true
