root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/goaway"
args_bin = [
    "--dnsport=6121",
    "--webserverport=8080",
    "--loglevel=0",
    "--disablelogging=false",
    "--auth=false",
    "--statisticsRetention=7",
]
cmd = 'go build -o goaway -ldflags="-X main.version=0.0.0" -o ./tmp/goaway .'
exclude_dir = ["assets", "tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
clean_on_exit = true
