services:
  goaway:
    image: pommee/goaway:latest
    build: .
    volumes:
      - goaway_data:/app
    container_name: goaway
    environment:
      - DNS_PORT=${DNS_PORT:-53}
      - WEBSITE_PORT=${WEBSITE_PORT:-8080}
    ports:
      - "${DNS_PORT:-53}:${DNS_PORT:-53}/udp"
      - "${DNS_PORT:-53}:${DNS_PORT:-53}/tcp"
      - "${WEBSITE_PORT:-8080}:${WEBSITE_PORT:-8080}/tcp"
    cap_add:
      - NET_BIND_SERVICE

volumes:
  goaway_data:
    name: goaway_data
