services:
  goaway:
    image: pommee/goaway:latest
    build: .
    volumes:
      - goaway_data:/app
    container_name: goaway
    environment:
      - DNS_PORT=${DNS_PORT}
      - WEBSITE_PORT=${WEBSITE_PORT}
    ports:
      - "${DNS_PORT}:${DNS_PORT}/udp"
      - "${DNS_PORT}:${DNS_PORT}/tcp"
      - "${WEBSITE_PORT}:${WEBSITE_PORT}/tcp"
    cap_add:
      - NET_BIND_SERVICE

volumes:
  goaway_data:
    name: goaway_data
